name: Deploy docks 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup@v3
        with: 
          node-version: 16
      
      - run: npm ci

      - run: npm run build

      - name: Deploy storybokk
        working-directory: ./packages/docs
        run: npm run deploy-storybokk -- --ci --existing-output-dir=storybokk-static
        env: 
          GH_TOKEN: "${{ github.actor }}: ${{ secrets.GITHUB_TOKEN}}

